cmock-config accepts Google Test directory (#19)

diff --git a/bin/cmock-config b/bin/cmock-config
--- a/bin/cmock-config
+++ b/bin/cmock-config
@@ -2,40 +2,75 @@
 
 function print_usage
 {
-	echo "cmock-config provides compilation and linker options required when using with cmock"
-	echo ""
-	echo "$0 OPTION [gmock [gtest]]"
+	echo "$0 OPTION [GOOGLE-TEST-DIRECTORY]"
+	echo "Provide compilation and linker options required by C Mock."
 	echo ""
 	echo "Options:"
-	echo -e "\t    --cflags   print compilation options"
-	echo -e "\t    --libs     print linker options"
-	echo -e "\t    additional linker options:"
-	echo -e "\t      [gmock]  path to libgmock"
-	echo -e "\t      [gtest]  path to libgtest"
-	echo -e "\t                defaults to [gmock]/gtest"
-	echo -e "\t-h, --help print help"
+	echo ""
+	echo "  --cflags   print compilation options"
+	echo "  --libs     print linker options"
+	echo "  -h, --help print help"
+	echo ""
+	echo "GOOGLE-TEST-DIRECTORY is a directory contaning downloaded and built Google Test."
 }
 
-if [ $# -lt 1 -o $# -gt 3 ] ; then
-	print_usage 1>&2
-	exit 1
-elif [ "$1" == --cflags -a $# -eq 1 ] ; then
-	DIR=`readlink -f $0`
-	DIR=`dirname $DIR`
-	DIR=`dirname $DIR`
+function check_directory
+{
+	DIR=$1
 
-	echo "-I$DIR/include"
-elif [ "$1" == --libs -a $# -le 3 ] ; then
-	if [ $# -eq 1 ] ; then
-		echo "-rdynamic -Wl,--no-as-needed -ldl"
-	elif [ $# -eq 2 ] ; then
-		echo "-rdynamic -Wl,--no-as-needed -ldl -L$2 -L$2/gtest"
+	if [ -e "$DIR" ]; then
+		if [ ! -d "$DIR" ]; then
+			echo "'$DIR' is not a directory."
+			exit 1
+		fi
 	else
-		echo "-rdynamic -Wl,--no-as-needed -ldl -L$2 -L$3"
+		echo "'$DIR' does not exist."
+		exit 1
 	fi
-elif [ "$1" == -h -o "$1" == --help ] ; then
-	print_usage
-else
+}
+
+function find_directories
+{
+	DIR=$(readlink -f "$1")
+	FILE_PATTERN=$2
+
+	find "$DIR" -regex $FILE_PATTERN -type f -exec dirname {} \; | sort | uniq
+}
+
+if [ $# -lt 1 -o $# -gt 2 ]; then
 	print_usage 1>&2
 	exit 1
 fi
+
+case $1 in
+	'--cflags')
+		CMOCK_DIR=$(dirname $(dirname $(readlink -f $0)))
+		OPTIONS="-I'$CMOCK_DIR/include'"
+
+		if [ $# -eq 2 ]; then
+			GTEST_DIR=$2
+			check_directory "$GTEST_DIR"
+			OPTIONS+=$(find_directories "$GTEST_DIR" '.*/\(gtest/gtest\.h\|gmock/gmock.h\)' | xargs -d '\n' dirname | xargs -d '\n' printf " -I'%s'")
+		fi
+
+		echo $OPTIONS
+		;;
+	'--libs')
+		OPTIONS="-rdynamic -Wl,--no-as-needed -ldl"
+
+		if [ $# -eq 2 ]; then
+			GTEST_DIR=$2
+			check_directory "$GTEST_DIR"
+			OPTIONS+=$(find_directories "$GTEST_DIR" '.*/\(libgtest\|libgmock\|libgmock_main\)\.a' | xargs -d '\n' printf " -L'%s'")
+		fi
+
+		echo $OPTIONS
+		;;
+	'-h'|'--help')
+		print_usage
+		;;
+	*)
+		print_usage 1>&2
+		exit 1
+		;;
+esac
